### ISSUE TITLE
Parse error of some documents (not all)

### ISSUE THREAD

**Issue by Ulli2k** [the-paperless-project/paperless#447] opened 2018-12-01 12:38 UTC
I do get an error by comsuming some documents.
In the log file I got the following message:
```
PARSE FAILURE for /home/paperless/consume/20181201132749Z - Vodafone_0.pdf: Convert failed at ('convert', '-scale', '500x5000', '-alpha', 'remove', '/home/paperless/consume/20181201132749Z - Vodafone_0.pdf[0]', '/tmp/paperless/paperless-kljps7vb/convert.png')
Consuming /home/paperless/consume/20181201132749Z - Vodafone_0.pdf
Parsers available: RasterisedDocumentParser
```

-----------------

The status of the consumer process showes the following
```
Dez 01 13:39:19 nuc python3[31976]: Consuming /home/paperless/consume/20181201132749Z-Vodafone_0.pdf
Dez 01 13:39:19 nuc python3[31976]: convert-im6.q16: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' -dFirstPage=1 -dLastPage=1 
Dez 01 13:39:19 nuc python3[31976]: convert-im6.q16: no images defined `/tmp/paperless/paperless-k3id431m/convert.png' @ error/convert.c/ConvertImageCommand/3258.
Dez 01 13:39:19 nuc python3[31976]: PARSE FAILURE for /home/paperless/consume/20181201132749Z-Vodafone_0.pdf: Convert failed at ('convert', '-scale', '500x5000', '-alpha', 'remove', '/home/paperless/consume/20181201132749Z-Vodafone_0.pdf[0]', '/tmp/paperless/paperless-k3id431m/convert.png')
```

I already tried to reprint the pdf file into an other but it does not work.
Any proposals?

**Comment by erikarvstedt** [comment] 2018-12-01 12:57
Can you share the file? Before sharing, you could remove sensitive data (while making sure the error still occurs).

**Comment by Ulli2k** [comment] 2018-12-01 13:46
see an example file in the following link:
[https://a.uguu.se/NuiksLNa5Zjx_20181201132749Z-VodafoneMIN.pdf](url)

**Comment by Ulli2k** [comment] 2018-12-01 17:55
I think it is not related to #439. I double checked the policy.xml.
It is already changed to "<policy domain="coder" rights="read|write" pattern="PDF" />"
Additionally, other pdf documents can be consumed, just this one not.

**Comment by danielquinn** [comment] 2018-12-01 18:38
Well the only thing weird that stands out for me is the `[0]` there in the error output.  I'm not sure where that's coming from, but it might be what's causing the problem.

I'd suggest trying out some debugging/print statements around where `convert` is called in the consumer and try to find out where that `[0]` is entering the process.

**Comment by Ulli2k** [comment] 2018-12-02 14:49
I found an work around.
convert 2 tiff and back to pdf. The pdf can be consumed without any error.....

**Comment by danielquinn** [comment] 2018-12-02 14:50
Weeeeeird.  But hey, if it works, don't knock it ;-)

**Comment by ovv** [comment] 2018-12-02 19:09
I face the same issue. It is indeed due to the `[0]` part. I haven't yet looked into the why.

**Comment by massaquah** [comment] 2018-12-06 21:10
I am having the exact same issue.
It started a few days ago. Don't know exactly what changed...
Just tried about 10 different pdfs and none of them got converted.

**Comment by iamjackg** [comment] 2018-12-09 19:18
The `[0]` seems to be there on purpose. See commit cac63494f04b8ab6278db2f4ce862e11efde2712.

**Comment by iamjackg** [comment] 2018-12-09 19:40
By using debug mode on ImageMagick when running the two commands, I can see that the `[0]` one fails with this:

```
2018-12-09T14:35:45-05:00 0:00.230 0.220u 7.0.7 Exception convert[94]: utility.c/ShredFile/1846/Exception
  Failed to remove: /tmp/magick-94q2ClEaGBBJbO
```

While without `[0]` the conversion proceeds normally.

**Comment by iamjackg** [comment] 2018-12-09 20:00
So looking around a bunch, it looks like IM+Gs is just a bit of a flakey combination with PDFs in general, and using `[0]` somehow makes things worse. This seems like an actual upstream issue, so I wonder if perhaps the right choice would be to take the inefficient route and just revert the `[0]` change.

**Comment by jat255** [comment] 2018-12-27 13:35
Hmm, I'm not sure why the single page optimization would cause this problem. I have not seen this at all, so my guess is it's an imagemagick problem specific to certain installations. I'm travelling currently, but I'll look at this more closely in the next day or so to see if I can find any IM bugs that are related or if I can reproduce. Thanks for hunting this down @colinfrei

**Comment by ovv** [comment] 2018-12-27 13:46
Would it be possible that some document are detected as one page when they are multiple ? For example empty white second page or no text detected on it ?

**Comment by stgarf** [comment] 2018-12-28 02:49
@jat255 may just not be using an updated imagemagick, like the one that may come in the docker image that some of us might be using.

I happen to have the problem (which seems seems to be caused by this PR (#399)) and I'm using the "official" docker image which contains `ImageMagick 7.0.7-32`.

```console
steve@one:~/Documents$ docker exec -it a279b7f2ae90 convert -version
Version: ImageMagick 7.0.7-32 Q16 x86_64 2018-11-21 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jpeg lcms ltdl pangocairo png ps rsvg tiff webp x xml zlib
```

**Comment by jat255** [comment] 2018-12-28 03:20
@stgarf Since I'm running Arch, I don't think I'm behind on software versions :wink: 

```
$ convert -version
Version: ImageMagick 7.0.8-14 Q16 x86_64 2018-10-24 https://imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
```

**Comment by stgarf** [comment] 2018-12-28 03:38
I wonder what causes the crashes inside the docker container for this specific invocation of imagemagick's convert binary... Can explore a gdb core dump a bit later.

**Comment by jat255** [comment] 2018-12-29 04:19
@colinfrei, the document that you shared processes fine on my system, so based off of @stgarf's investigations, I'm guessing it's a particular library issue. I'm not overly familiar with ImageMagick's internals, but it looks like this is happening when it tries to shred a temporary file. 

@stgarf, can you try the `convert` command from your previous example, but without the `[0]` to confirm it is the single-page syntax that is causing the problem? If so, this would appear to be an upstream bug, as that syntax should be supported (described under "Selecting frames" [here](https://imagemagick.org/script/command-line-processing.php))

As previously suggested, this behavior could be made configurable (even though it should work by default), but that's non-ideal due to the significant processing savings. Another option would be trying to do the extraction directly using ghostscript (which should be installed as a dependency, I believe), or bringing in another dependency like pdftk (should be avoided, if possible).

**Comment by jat255** [comment] 2018-12-29 04:30
Actually, it looks as though someone tested without the bracket syntax above. I have not the slightest idea why this would cause an issue; but my guess is an upstream bug. I agree with @iamjackg that IM is pretty flaky and opaque when it comes to PDF (especially when they fail). 

Can someone that's having this issue confirm they have Ghostscript installed? Issue https://github.com/danielquinn/paperless/issues/25 seems like it might be similar.

If we can't nail this down, my vote would be to rewrite this optimization to extract the single page using GS, then convert that for the thumbnail, and use the original (non-page-specific) syntax on that output to convert to png.

**Comment by colinfrei** [comment] 2018-12-29 05:53
I just confirmed that I do have Ghostscript installed (in docker):
```
$ docker exec paperless_consumer_1 gs --help
GPL Ghostscript 9.26 (2018-11-20)
Copyright (C) 2018 Artifex Software, Inc.  All rights reserved.
Usage: gs [switches] [file1.ps file2.ps ...]
...
```

**Comment by stgarf** [comment] 2018-12-29 06:16
Seems to be an imagemagick bug somehow. Dumping page the first page fails, but dumping the second page works without any problem.

```console
bash-4.4# convert two_page_test.pdf[0] page1.test  # We're just asking for page 1. This core dumps.
Aborted (core dumped)
bash-4.4# convert two_page_test.pdf[1] page2.test  # We're just asking for page 2 now. This works.
bash-4.4# ls -l
total 30684
-rwxrwxr--    1 root     root      31977472 Dec 29 05:33 core
-rw-r--r--    1 root     root         81764 Dec 29 05:34 page2.test
-rwxrwxr--    1 paperles paperles         0 Nov 17 12:27 remotely_mounted_directory
-rwxrwxr--    1 paperles paperles    109103 Dec 29 05:33 two_page_test.pdf
bash-4.4# 
```

I also have `gs` inside of the docker container and this invocation generates a single thumbnail (of the first page) from a multi-page pdf: 
`gs -q -sDEVICE=pngalpha -o %stdout% two_page_test.pdf | convert - two_page_test_thumb.png`

**Comment by JensPfeifle** [comment] 2019-01-08 19:30
Had the same issue using the official docker from [[60e8990](https://github.com/danielquinn/paperless/commit/60e8990a7b09f2944b9c344877094c40c7af3c70)] (Jan. 4 2019).

I've modified paperless_tesseract.get_thumbnail as follows:

```python
    def get_thumbnail(self):
        """
        The thumbnail of a PDF is just a 500px wide image of the first page.
        """

        out_path = os.path.join(self.tempdir, "convert.png")
        gs_out_path = os.path.join(self.tempdir, "gs_out.png")

        # Run convert to get a decent thumbnail

        # https://github.com/danielquinn/paperless/issues/447
        # call gs first
        environment = os.environ.copy()
        cmd = ["gs", "-q", "-sDEVICE=pngalpha",
               "-o", gs_out_path, self.document_path]
        if not subprocess.Popen(cmd, env=environment).wait() == 0:
            raise ParseError("Thumbnail (gs) failed at {}".format(cmd))
        # then run convert on the output from gs
        run_convert(
            self.CONVERT,
            "-scale", "500x5000",
            "-alpha", "remove",
            gs_out_path,
            out_path
        )

        return out_path
```

Not very pretty, but seems to work reliably.

**Comment by canthon** [comment] 2019-01-10 05:34
I was experiencing the same issue. 
Using JensPfeifle suggestion above worked for me too! Using gs instead of imagemagick seems to be a reasonable fix.

**Comment by stgarf** [comment] 2019-01-29 02:47
@JensPfeifle would you mind opening a PR to merge your fixes maybe?
Do people who use it outside of Docker have gs binary as well? Might need to consider that...

**Comment by ddddavidmartin** [comment] 2019-02-11 04:46
The fix for this issue in #494 is not integrated into the current Docker image yet, right? The fix was merged 13 days ago and the last Docker build was 15 days ago. Unfortunately Docker does not seem to show any more info than that.

Who is responsible for building the docker images? Or how can they be triggered? Thanks!

**Comment by ovv** [comment] 2019-02-11 08:12
I think they are only built for tagged version / releases: https://github.com/the-paperless-project/paperless/releases

**Comment by JensPfeifle** [comment] 2019-02-11 11:56
A fix is merged in @stgarf 's fork but the PR is still open in the official repository.
In the meantime, you could pull from [here](https://github.com/JensPfeifle/paperless/tree/fix_447) and start the containers with `docker-compose up -d --build` to build the images locally.

**Comment by Mattie112** [comment] 2019-02-11 14:17
I've also got a couple of documents (all my own scans went through no problem). If more files are needed let me know than I will see what I can upload.

**Comment by casidiablo** [comment] 2019-02-26 14:44
@JensPfeifle I'm using your image (pushed it to `cristianc/paperless`). Works like a charm. Waiting for your changes to make it upstream.

**Closed** 2019-03-08 20:45 UTC

**Comment by Tooa** [comment] 2020-01-05 13:59
Experienced the same problem described in this issue with the official docker image from [danielquinn/paperless:latest](https://hub.docker.com/layers/danielquinn/paperless/latest/images/sha256-e3aef495c56bfeceddf080195602ccc76bc488bca98ff1f148ddd1684c6e71c8). Looks like it was last updated a year ago. However, [a lot of contributions](https://github.com/the-paperless-project/paperless/compare/2.7.0...master) were merged to master since then. 

@danielquinn Are there any plans to release a new version to dockerhub? Is there an up-to-date community docker image on dockerhub I can use?
