### ISSUE TITLE
Error "Message subject is unsafe"

### ISSUE THREAD

**Issue by stilltldr** [the-paperless-project/paperless#659] opened 2020-05-18 07:30 UTC
Hi,

it seems as if paperless has a problem with the correspondent regex check when the subject contains "FWD:" and "AW:". When removing this prefix, the emails are processed.

https://github.com/the-paperless-project/paperless/blob/8698f92ac925baa335505b839125d97e325bb576/src/documents/models.py#L158

Using paperless from Docker:
`# ./manage.py --version

2.0.10
`
Regards

**Comment by MasterofJOKers** [comment] 2020-05-18 07:48
This should be a duplicate of #607

**Closed by MasterofJOKers** 2020-05-18 07:48 UTC

**Comment by stilltldr** [comment] 2020-05-18 07:54
No, it is a duplicate, thanks for pointing out!
